default_stages: [ push ]
repos:
  - repo: local
    hooks:
      - id: format
        name: Format
        stages: [ push ]
        language: system
        entry: make format
        types: [ python ]
      - id: lint
        name: Lint
        stages: [ push ]
        language: system
        entry: make lint
        types: [ python ]
  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout
        stages: [ commit ]
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.2.3
    hooks:
      - id: nbqa-black
        stages: [ commit ]
        args: [ --line-length=120, --target-version=py38 ]
      - id: nbqa-isort
        args: [ --profile=black, --project=production_code ]
        stages: [ commit ]

